export default function Privacy() {
  return (
    <div className="fb-col-wrapper pt-28 pb-20">
      {/* Header banner */}
      <div className="full-bleed bg-[#111] px-8 py-12 lg:px-20 text-center space-y-3">
        <span className="inline-flex items-center gap-2 bg-[#FACC14] text-black font-bold text-xs px-4 py-1.5 rounded-full border-2 border-black tracking-wider uppercase">
          📄 Legal
        </span>
        <h1 className="font-bold text-white text-[clamp(2rem,5vw,3rem)]">
          Privacy Policy
        </h1>
        <p className="text-gray-400 font-semibold text-sm">
          Last updated: November 27, 2025
        </p>
      </div>

      {/* Content */}
      <div className="max-w-[70ch] mx-auto space-y-6 pt-4 [&_h2]:font-bold [&_h2]:text-black [&_h2]:text-2xl [&_h2]:mt-10 [&_h2]:mb-3 [&_h3]:font-bold [&_h3]:text-black [&_h3]:text-lg [&_h3]:mt-6 [&_h3]:mb-2 [&_h4]:font-bold [&_h4]:text-black [&_h4]:mt-4 [&_p]:text-gray-600 [&_p]:font-semibold [&_p]:text-sm [&_p]:leading-relaxed [&_ul]:space-y-2 [&_li]:text-gray-600 [&_li]:font-semibold [&_li]:text-sm [&_a]:underline [&_a]:underline-offset-2 [&_a]:text-[#A855F7] [&_a:hover]:opacity-70 [&_strong]:text-black">
        <p>
          This Privacy Policy describes Our policies and procedures on the
          collection, use and disclosure of Your information when You use the
          Service and tells You about Your privacy rights and how the law
          protects You.
        </p>
        <p>
          We use Your Personal data to provide and improve the Service. By using
          the Service, You agree to the collection and use of information in
          accordance with this Privacy Policy.
        </p>
        <h2>Interpretation and Definitions</h2>
        <h3>Interpretation</h3>
        <p>
          The words whose initial letters are capitalized have meanings defined
          under the following conditions. The following definitions shall have
          the same meaning regardless of whether they appear in singular or in
          plural.
        </p>
        <h3>Definitions</h3>
        <p>For the purposes of this Privacy Policy:</p>
        <ul className="list-none space-y-3">
          {[
            {
              term: "Account",
              def: "means a unique account created for You to access our Service or parts of our Service.",
            },
            {
              term: "Affiliate",
              def: 'means an entity that controls, is controlled by, or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.',
            },
            {
              term: "Company",
              def: 'referred to as either "the Company", "We", "Us" or "Our" in this Agreement, refers to The Future Star Contest, Irama Complex, Plot 4, Sa\'adu, Zungur Avenue, off Wole Soyinka Avenue, 4th Avenue, Gwarinpa, Abuja.',
            },
            {
              term: "Cookies",
              def: "are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.",
            },
            { term: "Country", def: "refers to: Nigeria" },
            {
              term: "Device",
              def: "means any device that can access the Service such as a computer, a cell phone or a digital tablet.",
            },
            {
              term: "Personal Data",
              def: "is any information that relates to an identified or identifiable individual.",
            },
            { term: "Service", def: "refers to the Website." },
            {
              term: "Usage Data",
              def: "refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.",
            },
          ].map(({ term, def }) => (
            <li key={term} className="border-l-4 border-[#FACC14] pl-4">
              <strong>{term}</strong> — {def}
            </li>
          ))}
        </ul>

        <h2>Collecting and Using Your Personal Data</h2>
        <h3>Types of Data Collected</h3>
        <h4>Personal Data</h4>
        <p>
          While using Our Service, We may ask You to provide Us with certain
          personally identifiable information that can be used to contact or
          identify You. This may include:
        </p>
        <ul className="list-disc list-inside">
          <li>First name and last name</li>
          <li>Phone number</li>
          <li>Usage Data</li>
        </ul>

        <h4>Usage Data</h4>
        <p>Usage Data is collected automatically when using the Service.</p>
        <p>
          Usage Data may include information such as Your Device&apos;s Internet
          Protocol address, browser type, browser version, the pages of our
          Service that You visit, the time and date of Your visit, and other
          diagnostic data.
        </p>

        <h4>Tracking Technologies and Cookies</h4>
        <p>
          We use Cookies and similar tracking technologies to track the activity
          on Our Service and store certain information. Technologies We use may
          include:
        </p>
        <ul className="list-disc list-inside">
          <li>
            <strong>Cookies or Browser Cookies.</strong> A cookie is a small
            file placed on Your Device. You can instruct Your browser to refuse
            all Cookies.
          </li>
          <li>
            <strong>Web Beacons.</strong> Certain sections of our Service may
            contain small electronic files known as web beacons that permit the
            Company to count users who have visited those pages.
          </li>
        </ul>

        <h3>Use of Your Personal Data</h3>
        <p>The Company may use Personal Data for the following purposes:</p>
        <ul className="list-disc list-inside">
          <li>
            <strong>To provide and maintain our Service</strong>
          </li>
          <li>
            <strong>To manage Your Account</strong>
          </li>
          <li>
            <strong>For the performance of a contract</strong>
          </li>
          <li>
            <strong>To contact You</strong> regarding updates and services
          </li>
          <li>
            <strong>To manage Your requests</strong>
          </li>
          <li>
            <strong>For business transfers</strong>
          </li>
        </ul>

        <h3>Retention of Your Personal Data</h3>
        <p>
          The Company will retain Your Personal Data only for as long as is
          necessary for the purposes set out in this Privacy Policy.
        </p>

        <h3>Security of Your Personal Data</h3>
        <p>
          The security of Your Personal Data is important to Us. While We strive
          to use commercially reasonable means to protect Your Personal Data, We
          cannot guarantee its absolute security.
        </p>

        <h2>Children&apos;s Privacy</h2>
        <p>
          Our Service does not address anyone under the age of 13. We do not
          knowingly collect personally identifiable information from anyone
          under the age of 13. If You are a parent and become aware that Your
          child has provided Us with Personal Data, please contact Us.
        </p>

        <h2>Changes to this Privacy Policy</h2>
        <p>
          We may update Our Privacy Policy from time to time. We will notify You
          of any changes by posting the new Privacy Policy on this page and
          updating the &quot;Last updated&quot; date.
        </p>

        <h2>Contact Us</h2>
        <div className="bg-[#FACC14] border-2 border-black rounded-2xl px-6 py-5 shadow-[4px_4px_0px_#111]">
          <p className="font-bold text-black">
            If you have any questions about this Privacy Policy, contact us at:
          </p>
          <p className="font-bold text-black mt-1">
            📧{" "}
            <a
              href="mailto:hello@leadritehub.com"
              className="text-black underline">
              hello@kidscrown.net
            </a>
          </p>
        </div>
      </div>
    </div>
  );
}
